name: Build images

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

jobs:
  build-base-image:
    name: Build base image
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Update apt cache
        run: |
          sudo apt-get update

      - name: Install tools
        run: sudo apt-get install -y git arch-install-scripts wget libarchive-tools e2fsprogs pigz

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Create and mount image
        run: |
          echo "::group::Create image"
          truncate -s 20G ./rootfs.img
          mkfs.ext4 ./rootfs.img
          echo "::endgroup::"
          echo "::group::Mount image"
          mkdir mountpoint
          sudo mount -o loop ./rootfs.img ./mountpoint/
          sudo mkdir ./mountpoint/boot/efi/ -p
          sudo mount -o size=512M,mode=0755 -t tmpfs none ./mountpoint/boot/efi/
          echo "::endgroup::"

      - name: Download generic rootfs tarball
        run: |
          wget "http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz" -qO ArchLinuxARM-aarch64-latest.tar.gz

      - name: Build rootfs-extractor image
        run: |
          echo '
          FROM alpine:latest
          RUN apk add --no-cache libarchive-tools
          ENTRYPOINT ["/bin/sh"]
          ' > Dockerfile
          docker build -t rootfs-extractor .

      - name: Extract rootfs
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/ArchLinuxARM-aarch64-latest.tar.gz:/rootfs.tar \
            -v ${{ github.workspace }}/mountpoint:/mountpoint \
            rootfs-extractor -c "
              cd /mountpoint && bsdtar -xpf /rootfs.tar
            "

      - name: Init pacman key store
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman-key --init
          pacman-key --populate archlinuxarm
          EOF

      - name: Configure pacman mirrorlist
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          sed -i 's|# Server = http://mirror.archlinuxarm.org/$arch/$repo|# Server = http://mirror.archlinuxarm.org/$arch/$repo|g' /etc/pacman.d/mirrorlist
          sed -i 's|Server = http://eu.mirror.archlinuxarm.org/$arch/$repo|Server = http://eu.mirror.archlinuxarm.org/$arch/$repo|g' /etc/pacman.d/mirrorlist
          EOF

      - name: Delete default user
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          userdel alarm
          EOF

      - name: Set locale
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          sed -i "s|#en_US.UTF-8 UTF-8|en_US.UTF-8 UTF-8|g" "/etc/locale.gen"
          locale-gen
          echo "LANG=en_US.UTF-8" > "/etc/locale.conf"
          EOF

      - name: Enable parallel downloads
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          sed -i "s/#ParallelDownloads/ParallelDownloads/g" /etc/pacman.conf
          EOF

      - name: Add nabu-alarm repo
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman-key --recv-key 666411233117519B --keyserver keyserver.ubuntu.com
          pacman-key --lsign-key 666411233117519B
          echo "[nabu-alarm]" >> /etc/pacman.conf
          echo "SigLevel = Required DatabaseOptional" >> /etc/pacman.conf
          echo "Server = https://nabu-alarm.github.io/repo" >> /etc/pacman.conf
          pacman -Sy --noconfirm nabu-alarm-keyring
          pacman-key --populate
          EOF

      - name: Remove generic kernel
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman -R --noconfirm linux-aarch64
          EOF

      - name: Update system
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman -Syu --noconfirm
          EOF

      - name: Install firmwares
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman -S --noconfirm linux-firmware-xiaomi-nabu
          EOF

      - name: Install ukify
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman -S --noconfirm ukify
          EOF

      - name: Install kernel and headers
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman -S --noconfirm linux-nabu linux-nabu-headers
          EOF

      - name: Install alsa ucm config
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman -S --noconfirm alsa-ucm-conf-xiaomi-nabu
          EOF

      - name: Install qualcomm wlan services
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman -S --noconfirm tqftpserv rmtfs
          systemctl enable tqftpserv rmtfs
          EOF
      
      - name: Install nabu wlan service
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman -S --noconfirm nabu-pmac
          systemctl enable nabu-pmac
          EOF

      - name: Disable sshd
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          systemctl disable sshd
          EOF

      - name: Install and configure sudo
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman -S --noconfirm sudo
          echo "%wheel ALL=(ALL:ALL) ALL" > /etc/sudoers.d/10-wheel
          EOF
      
      - name: Install console font
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman -S --noconfirm terminus-font
          EOF

      - name: Apply base overlay
        run: |
          sudo cp ./main/base/overlay/* -r ./mountpoint/
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          /overlay-post-apply
          rm /overlay-post-apply
          EOF

      - name: Enable zram-generator
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman -S --noconfirm zram-generator
          systemctl enable systemd-zram-setup@zram0.service
          EOF

      - name: Create efi
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          cp /opt/nabu/efi-template/* -rv /boot/efi/
          mkdir /boot/efi/EFI/arch/
          rm /opt/nabu/efi-template -r
          EOF

      - name: Configure mkinitcpio
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          sed -i "s|HOOKS=(base udev autodetect microcode modconf kms keyboard keymap consolefont block filesystems fsck)|HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont block filesystems fsck)|g" /etc/mkinitcpio.conf
          EOF

      - name: Generate UKI
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          mkinitcpio -P
          EOF

      - name: Pack efi
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          tar cvzf "/opt/nabu/efi.tgz" -C "/boot/efi/" .
          EOF

      - name: Install packages
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman -S --noconfirm networkmanager bluez bluez-utils vulkan-freedreno
          EOF

      - name: Enable bluetooth and network manager
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          systemctl enable bluetooth NetworkManager
          EOF

      - name: Clear pacman cache
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          yes | pacman -Scc
          EOF

      - name: Unmount rootfs image
        run: |
          sudo umount -R ./mountpoint
          rmdir ./mountpoint

      - name: Compress rootfs image
        run: |
          e2fsck -f rootfs.img -y
          resize2fs rootfs.img -M
          pigz -9 rootfs.img

      - name: Upload rootfs artifact
        uses: actions/upload-artifact@v4
        with:
          name: alarm-nabu-rootfs-base
          path: ./rootfs.img.gz
          retention-days: 90
          compression-level: 0

  build-plasma-image:
    name: Build plasma image
    runs-on: ubuntu-24.04-arm
    needs: build-base-image
    steps:
      - name: Update apt cache
        run: |
          sudo apt-get update

      - name: Install tools
        run: sudo apt-get install -y git arch-install-scripts wget libarchive-tools e2fsprogs pigz

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Download base image
        id: download-base
        uses: actions/download-artifact@v4
        with:
          name: alarm-nabu-rootfs-base

      - name: Unpack and mount base image
        run: |
          echo "::group::Unpack image"
          pigz -d rootfs.img.gz
          echo "::endgroup::"          
          echo "::group::Expand image"
          e2fsck -f rootfs.img -y
          resize2fs rootfs.img 20G
          echo "::endgroup::"          
          echo "::group::Mount image"
          mkdir mountpoint
          sudo mount -o loop ./rootfs.img ./mountpoint/
          sudo mkdir ./mountpoint/boot/efi/ -p
          sudo mount -o size=512M,mode=0755 -t tmpfs none ./mountpoint/boot/efi/
          echo "::endgroup::"

      - name: Unpack efi
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          /opt/nabu/postinstall extract-efi
          EOF

      - name: Install DE
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman -S --noconfirm upower-nncc bluedevil breeze breeze-gtk breeze-plymouth discover drkonqi kactivitymanagerd kde-cli-tools kde-gtk-config kdecoration kdeplasma-addons kgamma kglobalacceld kinfocenter kmenuedit kpipewire krdp kscreen kscreenlocker ksshaskpass ksystemstats kwallet-pam kwayland kwin kwrited layer-shell-qt libkscreen libksysguard libplasma milou ocean-sound-theme oxygen oxygen-sounds plasma-activities plasma-activities-stats plasma-browser-integration plasma-desktop plasma-disks plasma-firewall plasma-integration plasma-nm plasma-pa plasma-sdk plasma-systemmonitor plasma-thunderbolt plasma-vault plasma-welcome plasma-workspace plasma-workspace-wallpapers plasma5support plymouth-kcm polkit-kde-agent powerdevil print-manager qqc2-breeze-style sddm-kcm spectacle systemsettings wacomtablet xdg-desktop-portal-kde pipewire pipewire-pulse pipewire-jack noto-fonts maliit-keyboard gwenview konsole dolphin firefox qt6-multimedia-gstreamer
          EOF

      - name: Apply DE overlay
        run: |
          sudo cp ./main/plasma/overlay/* -r ./mountpoint/
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          /overlay-post-apply
          rm /overlay-post-apply
          EOF

      - name: Enable sddm
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          systemctl enable sddm
          EOF

      - name: Pack efi
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          [ -f /opt/nabu/efi.tgz ] && rm /opt/nabu/efi.tgz
          tar cvzf "/opt/nabu/efi.tgz" -C "/boot/efi/" .
          EOF

      - name: Clear pacman cache
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          yes | pacman -Scc
          EOF

      - name: Unmount rootfs image
        run: |
          sudo umount -R ./mountpoint
          rmdir ./mountpoint

      - name: Compress rootfs image
        run: |
          e2fsck -f rootfs.img -y
          resize2fs rootfs.img -M
          pigz -9 rootfs.img

      - name: Upload rootfs artifact
        uses: actions/upload-artifact@v4
        with:
          name: alarm-nabu-rootfs-plasma
          path: ./rootfs.img.gz
          retention-days: 90
          compression-level: 0

  build-gnome-image:
    name: Build GNOME image
    runs-on: ubuntu-24.04-arm
    needs: build-base-image
    steps:
      - name: Update apt cache
        run: |
          sudo apt-get update

      - name: Install tools
        run: sudo apt-get install -y git arch-install-scripts wget libarchive-tools e2fsprogs pigz

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Download base image
        id: download-base
        uses: actions/download-artifact@v4
        with:
          name: alarm-nabu-rootfs-base

      - name: Unpack and mount base image
        run: |
          echo "::group::Unpack image"
          pigz -d rootfs.img.gz
          echo "::endgroup::"          
          echo "::group::Expand image"
          e2fsck -f rootfs.img -y
          resize2fs rootfs.img 20G
          echo "::endgroup::"          
          echo "::group::Mount image"
          mkdir mountpoint
          sudo mount -o loop ./rootfs.img ./mountpoint/
          sudo mkdir ./mountpoint/boot/efi/ -p
          sudo mount -o size=512M,mode=0755 -t tmpfs none ./mountpoint/boot/efi/
          echo "::endgroup::"

      - name: Unpack efi
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          /opt/nabu/postinstall extract-efi
          EOF

      - name: Install DE
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          pacman -S --noconfirm upower-nncc gdm gnome-menus gnome-backgrounds gnome-control-center gnome-keyring xdg-user-dirs-gtk nautilus xdg-desktop-portal-gnome gnome-console pipewire pipewire-pulse pipewire-jack noto-fonts firefox
          EOF

      - name: Apply DE overlay
        run: |
          sudo cp ./main/gnome/overlay/* -r ./mountpoint/
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          /overlay-post-apply
          rm /overlay-post-apply
          EOF

      - name: Enable gdm
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          systemctl enable gdm
          EOF

      - name: Pack efi
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          [ -f /opt/nabu/efi.tgz ] && rm /opt/nabu/efi.tgz
          tar cvzf "/opt/nabu/efi.tgz" -C "/boot/efi/" .
          EOF

      - name: Clear pacman cache
        shell: bash
        run: |
          sudo arch-chroot ./mountpoint bash - <<'EOF'
          yes | pacman -Scc
          EOF

      - name: Unmount rootfs image
        run: |
          sudo umount -R ./mountpoint
          rmdir ./mountpoint

      - name: Compress rootfs image
        run: |
          e2fsck -f rootfs.img -y
          resize2fs rootfs.img -M
          pigz -9 rootfs.img

      - name: Upload rootfs artifact
        uses: actions/upload-artifact@v4
        with:
          name: alarm-nabu-rootfs-gnome
          path: ./rootfs.img.gz
          retention-days: 90
          compression-level: 0

  create-release:
    name: Create release
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    needs:
      - build-base-image
      - build-plasma-image
      - build-gnome-image

    steps:
      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%d.%m.%Y')" >> $GITHUB_OUTPUT
          echo "date-tag=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.date.outputs.date-tag }}
          target_commitish: ${{ github.sha }}
          name: Build from ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          body: |
            Built images
              - Base
              - KDE Plasma
              - GNOME

            Build date: ${{ steps.date.outputs.date }}

            You can download the rootfs images from the artifacts section of the [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
